# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30, verbose_name='公司名称')),
                ('campany_addr', models.CharField(blank=True, max_length=10, null=True, verbose_name='公司地址')),
                ('campany_url', models.CharField(blank=True, max_length=10, null=True, verbose_name='公司链接')),
                ('campany_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='规模')),
                ('industry', models.CharField(blank=True, max_length=20, null=True, verbose_name='行业')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
    ]
