# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=10, verbose_name='岗位代码')),
                ('job_name', models.CharField(max_length=30, verbose_name='岗位名称')),
                ('salary', models.CharField(blank=True, max_length=10, null=True, verbose_name='薪资')),
                ('recruit_num', models.CharField(blank=True, max_length=10, null=True, verbose_name='招聘人数')),
                ('work_year', models.CharField(blank=True, max_length=20, null=True, verbose_name='经验')),
                ('study', models.CharField(blank=True, max_length=10, null=True, verbose_name='学历')),
                ('work_addr', models.CharField(blank=True, max_length=255, null=True, verbose_name='工作地址')),
                ('jd', models.TextField(blank=True, max_length=255, null=True, verbose_name='岗位描述')),
                ('workfare', models.TextField(blank=True, max_length=255, null=True, verbose_name='福利')),
            ],
            options={
                'verbose_name': '岗位详情',
                'verbose_name_plural': '岗位详情',
            },
        ),
    ]
