# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30, verbose_name='城市')),
                ('city_name', models.CharField(max_length=30, verbose_name='城市名称')),
                ('city_url', models.CharField(blank=True, max_length=10, null=True, verbose_name='城市链接')),
            ],
            options={
                'verbose_name': '城市信息',
                'verbose_name_plural': '城市信息',
            },
        ),
    ]
