# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-24 06:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('jobs', '0001_initial'),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobRealation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('put_time', models.DateField(verbose_name='添加时间')),
                ('job_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='岗位链接')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.CityInfo')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='companies.CompanyProfile')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.JobInfo')),
            ],
        ),
    ]
