# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='industries',
            old_name='co_id',
            new_name='industry_id',
        ),
    ]
