# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 15:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20190507_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industries',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='行业'),
        ),
    ]
