# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20190507_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='co_id',
            field=models.CharField(db_index=True, default=None, max_length=255, unique=True, verbose_name='公司代码'),
        ),
        migrations.AddField(
            model_name='companies',
            name='img_url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='头像链接'),
        ),
        migrations.AddField(
            model_name='companies',
            name='note_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注_城市'),
        ),
        migrations.AddField(
            model_name='companies',
            name='note_industry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注_行业'),
        ),
        migrations.AddField(
            model_name='companies',
            name='quality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='性质'),
        ),
        migrations.AddField(
            model_name='companies',
            name='size',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='规模'),
        ),
        migrations.AddField(
            model_name='companies',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='city.Cities', verbose_name='城市'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='industries',
            field=models.ManyToManyField(blank=True, null=True, to='company.Industries', verbose_name='行业'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='地址'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='公司名'),
        ),
        migrations.AlterField(
            model_name='industries',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='行业'),
        ),
    ]
