# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 12:22
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCollectJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.Jobs', verbose_name='岗位')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户收藏岗位',
                'verbose_name_plural': '用户收藏岗位',
                'db_table': 'user_collect_job',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserFocusCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Companies', verbose_name='公司')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户关注公司',
                'verbose_name_plural': '用户关注公司',
                'db_table': 'user_focus_company',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserFocusIndustry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Industries', verbose_name='行业')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户关注行业',
                'verbose_name_plural': '用户关注行业',
                'db_table': 'user_focus_industry',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='UserFocusJobFunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('jobfunction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.JobFunctions', verbose_name='行业')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户关注职能',
                'verbose_name_plural': '用户关注职能',
                'db_table': 'user_focus_jobfunction',
                'ordering': ['-create_time'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='userfocusjobfunction',
            unique_together=set([('user', 'jobfunction')]),
        ),
        migrations.AlterUniqueTogether(
            name='userfocusindustry',
            unique_together=set([('user', 'industry')]),
        ),
        migrations.AlterUniqueTogether(
            name='userfocuscompany',
            unique_together=set([('user', 'company')]),
        ),
        migrations.AlterUniqueTogether(
            name='usercollectjob',
            unique_together=set([('user', 'job')]),
        ),
    ]
