# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-28 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='isUndercarriage',
            field=models.BooleanField(default=False, verbose_name='是否下架'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.IntegerField(verbose_name='工作id'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='jobfunction',
            field=models.ManyToManyField(default=None, to='job.JobFunctions', verbose_name='职能'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_high',
            field=models.IntegerField(verbose_name='工资_高'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_low',
            field=models.IntegerField(verbose_name='工资_低'),
        ),
    ]
