# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobfunctions',
            name='category',
            field=models.ForeignKey(blank=True, max_length=255, null=True, on_delete=django.db.models.deletion.CASCADE, to='job.JobFunctions', verbose_name='职能分类'),
        ),
        migrations.AddField(
            model_name='jobfunctions',
            name='fun_id',
            field=models.CharField(db_index=True, default=None, max_length=255, unique=True, verbose_name='职能代码'),
        ),
        migrations.AddField(
            model_name='jobfunctions',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='jobfunctions',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='职能'),
        ),
    ]
