# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20190507_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobfunctions',
            name='fun_id',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='职能代码'),
        ),
        migrations.AlterField(
            model_name='jobfunctions',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='职能'),
        ),
    ]
