# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 22:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_auto_20190507_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='co_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注_企业'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='note_city',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注_城市'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='note_education',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注_学历'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='note_func',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注_职能'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.Companies', verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='isUndercarriage',
            field=models.BooleanField(default=False, verbose_name='是否关闭'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='job_id',
            field=models.IntegerField(unique=True, verbose_name='工作id'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='put_time',
            field=models.DateField(blank=True, null=True, verbose_name='发布时间'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_high',
            field=models.IntegerField(blank=True, null=True, verbose_name='工资_高'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='salary_low',
            field=models.IntegerField(blank=True, null=True, verbose_name='工资_低'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='work_year',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='工作经验'),
        ),
    ]
