# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-07 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='city_zh',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='城市名'),
        ),
        migrations.AddField(
            model_name='cities',
            name='url',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='cities',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='城市'),
        ),
    ]
